export const actionTypes = {
  SET_POSTS: "SET_POSTS",
  SET_USERS: "SET_USERS",
  LOGIN_USER: "LOGIN_USER",
  SET_SORT_BY: "SET_SORT_BY",
  GET_BOOKMARKS: "GET_BOOKMARKS",
  ADD_BOOKMARK: "ADD_BOOKMARK",
  REMOVE_BOOKMARK: "REMOVE_BOOKMARK",
  EDIT_USER_PROFILE: "EDIT_USER_PROFILE",
  FOLLOW_USER: "FOLLOW_USER",
  UNFOLLOW_USER: "UNFOLLOW_USER",
};
